name: chic-secret
version: 0.1.0
summary: Chic Secret
description: A password manager made in Flutter

confinement: strict
base: core18
grade: stable

slots:
  dbus-chic-secret:
    interface: dbus
    bus: session
    name: org.bar.chic_secret
    
apps:
  chic-secret:
    command: chic_secret
    extensions: [flutter-beta]
    plugs:
    - network
    slots:
      - dbus-chic-secret
parts:
  chic-secret:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
